Update the script to test the latest version for all crates.

diff --git a/latest_version b/latest_version
--- a/latest_version
+++ b/latest_version
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
 function test_latest_vesion () {
-    editor="$1"
+    check_dir="$1"
+    editor="$2"
     hash "${editor}" >/dev/null 2>&1
     if [ $? -ne 0 ]; then
         editor=""
@@ -10,7 +11,7 @@ function test_latest_vesion () {
         crate="$(echo ${crate_dir} | cut -d'/' -f 2)"
         commit_id="$(git log --pretty=oneline -1 ${crate_dir} | cut -c 1-7)"
         printf "Commit %s for %s\n" "${commit_id}" "${crate}"
-        find . -mindepth 2 -name "Cargo.toml" \
+        find "${check_dir}" -name "Cargo.toml" \
                 -exec grep -H "${crate}[^-a-Z0-9_]" {} \; \
                 | grep sharelibs | grep rev | grep -v "${commit_id}" \
                 | while read cargoline; do
@@ -24,7 +25,14 @@ function test_latest_vesion () {
 }
 
 function main () {
-    test_latest_vesion "$1"
+    local check_dir="$1"
+    local editor="$2"
+    if [ -d "${check_dir}" ]; then
+        test_latest_vesion "${check_dir}" "${editor}"
+    else
+        echo "[Error] first param has to be a directory."
+        exit 1
+    fi
 }
 
 main "$@"
